#!/usr/bin/env python3
"""
Create minimal autoformalization.json for testing BEQ equivalence checking.

This script creates dummy autoformalization results for a few CONNF problems
so you can test the equivalence checker without running the full auto-formalization pipeline.
"""

import json
from pathlib import Path

# Load CONNF benchmark
with open('data/connf/benchmark.jsonl', 'r') as f:
    problems = [json.loads(line) for line in f if line.strip()]

# Take first 5 problems as test set
test_problems = problems[:5]

# Create minimal autoformalization results
# Format: {problem_name: [list of attempts]}
autoformalization_result = {}

for prob in test_problems:
    full_name = prob['full_name']
    formal_stmt = prob['formal_stmt']

    # Create one "fake" autoformalization attempt using ground truth
    # In real use, this would be generated by LLM
    autoformalization_result[full_name] = [
        {
            "autoformalized_statement": formal_stmt,
            "typecheck_result": {
                "is_success": True,
                "lean_env": 1
            }
        }
    ]

    print(f"Added: {full_name}")

# Save to working directory
output_file = Path('/mnt/disk0/t00917290/result/autoformalization.json')
output_file.parent.mkdir(parents=True, exist_ok=True)

with open(output_file, 'w') as f:
    json.dump(autoformalization_result, f, indent=2)

print(f"\nCreated {output_file}")
print(f"Total problems: {len(autoformalization_result)}")
print("\nNow you can run:")
print("  python -m equivalence.beq_basic \\")
print("    --equiv_url http://localhost:13423/v1 \\")
print("    --equiv_model Qwen3_coder \\")
print("    --eval_set connf \\")
print("    --working_root /mnt/disk0/t00917290/result \\")
print("    --dataset_root ./data/ \\")
print("    --mathlib_root /path/to/mathlib4 \\")
print("    --repl_root /path/to/repl \\")
print("    --num_concurrency 1 \\")
print("    --try_num 1")
